#!/usr/bin/expect

log_user 1
set timeout 9

spawn jdb -attach 5005

expect ".*VM Started.*"

# send "stop at Test:10"
# send "stop at Test:12"

# send "run"
# send "5 step"
# expect ".*"
# puts $expect_out(buffer)

send "run\r"

send "exit\r"

close


